In [1]:
import torch
import numpy as np

C:\Users\22789\Anaconda3\envs\pytorch_py\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
torch.__version__

'1.8.0+cpu'

In [3]:
s = 'Life if note easy for any of us!!!!'

In [4]:
s

'Life if note easy for any of us!!!!'

In [5]:
import string

In [6]:
for c in string.punctuation:
    s = s.replace(c,' ')
s

'Life if note easy for any of us    '

# 分词方式（一）

In [7]:
list(s)

['L',
 'i',
 'f',
 'e',
 ' ',
 'i',
 'f',
 ' ',
 'n',
 'o',
 't',
 'e',
 ' ',
 'e',
 'a',
 's',
 'y',
 ' ',
 'f',
 'o',
 'r',
 ' ',
 'a',
 'n',
 'y',
 ' ',
 'o',
 'f',
 ' ',
 'u',
 's',
 ' ',
 ' ',
 ' ',
 ' ']

# 分词方式（二）

In [8]:
 s.split()

['Life', 'if', 'note', 'easy', 'for', 'any', 'of', 'us']

# 分词方式（三）：n-gram

In [9]:
np.unique(s.split())

array(['Life', 'any', 'easy', 'for', 'if', 'note', 'of', 'us'],
      dtype='<U4')

In [10]:
vocab = dict((word,index) for index,word in enumerate(np.unique(s.split())))

In [11]:
vocab

{'Life': 0,
 'any': 1,
 'easy': 2,
 'for': 3,
 'if': 4,
 'note': 5,
 'of': 6,
 'us': 7}

In [12]:
s = [vocab.get(w) for w in s.split()]

In [13]:
s

[0, 4, 5, 2, 3, 1, 6, 7]

In [14]:
len(s),len(vocab)

(8, 8)

In [15]:
b = np.zeros((len(s),len(vocab)))

In [16]:
b #ont-hot独热编码

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
for index ,i in enumerate(s):
    b[index][i] = 1 

In [18]:
b[:5]

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [19]:
em = torch.nn.Embedding(len(vocab),20) #创建词嵌入层

In [20]:
s_em = em(torch.LongTensor(s))

In [21]:
s_em

tensor([[ 0.8043,  0.2025, -0.2322,  1.1830, -1.9251,  0.7770, -1.5130,  0.0553,
         -0.1787, -1.7870, -1.4918,  1.5060,  0.0532, -1.4687, -0.7460,  0.6418,
         -0.5948, -1.4349, -0.2315,  0.4025],
        [-0.0486,  0.5332, -0.9912, -0.1938, -1.3800,  0.9525,  0.7056,  0.3514,
          0.5177,  0.7527,  0.1624, -0.6584, -0.9087, -0.0317,  0.6123, -0.0462,
         -2.2782,  0.0387, -0.2960, -1.4057],
        [ 1.6289,  0.3631,  0.9225, -1.4985, -2.2496,  0.3454, -1.1342,  0.1279,
          1.1911, -0.4829, -0.2632, -0.7101, -0.5023, -0.0675, -0.6350, -0.6557,
         -0.7364, -0.3479, -0.6129,  1.0988],
        [-0.2968,  0.1930, -1.5040, -2.6566,  0.1331, -1.6100, -0.8090,  1.8707,
         -0.5620,  0.5118,  1.4130,  0.8767,  0.5468,  0.6129, -0.7945, -0.5098,
         -0.1643, -0.6918,  0.5686,  0.4851],
        [ 0.9984,  0.3840, -0.3279,  0.3544,  1.0047,  0.2022, -0.0081,  0.5688,
         -1.0010, -1.1797,  1.2203,  1.9071, -1.9089,  1.3055, -0.9494, -1.4278,
      

## 嵌入层还用于所有分类输入，而不只是为自然语言进行词嵌入
## 例如，如果你要为超市里多个商品做推荐，则最好对商品名词做词嵌入，而不是将他们作为单热编码向量输入送给网络

In [165]:
import torch
import torchtext
import numpy as np 
import torch.nn as nn
import torch.nn.functional as F
from torchtext.vocab import GloVe #词嵌入表示得库
from torchtext.legacy.data import Field,dataset
from torchtext.vocab import GloVe

In [31]:
TEXT = Field(lower=True,fix_length=200,batch_first=True)
LABEL = Field(sequential=False)

In [32]:
train,test=torchtext.legacy.datasets.IMDB.splits(TEXT,LABEL)

downloading aclImdb_v1.tar.gz


E:\python_project\PyQt5\.data\imdb\aclImdb_v1.tar.gz: 100%|████████████████████████| 84.1M/84.1M [07:25<00:00, 189kB/s]


In [56]:
train.fields

{'text': <torchtext.legacy.data.field.Field at 0x23cbb317af0>,
 'label': <torchtext.legacy.data.field.Field at 0x23cbb317e50>}

In [57]:
TEXT.build_vocab(train,max_size=10000,min_freq=3)
LABEL.build_vocab(train)

In [58]:
TEXT.vocab.freqs

Counter({'bromwell': 8,
         'high': 1707,
         'is': 104171,
         'a': 159953,
         'cartoon': 386,
         'comedy.': 388,
         'it': 65505,
         'ran': 218,
         'at': 22731,
         'the': 322198,
         'same': 3770,
         'time': 7945,
         'as': 45102,
         'some': 15280,
         'other': 8229,
         'programs': 42,
         'about': 16486,
         'school': 1140,
         'life,': 715,
         'such': 4812,
         '"teachers".': 2,
         'my': 11766,
         '35': 55,
         'years': 3335,
         'in': 90527,
         'teaching': 73,
         'profession': 43,
         'lead': 1120,
         'me': 7722,
         'to': 133967,
         'believe': 2310,
         'that': 66292,
         "high's": 1,
         'satire': 182,
         'much': 8739,
         'closer': 184,
         'reality': 631,
         'than': 9807,
         'scramble': 5,
         'survive': 180,
         'financially,': 3,
         'insightful': 50,
    

In [61]:
TEXT.vocab.stoi

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x0000023CEEF17AF0>>,
            {'<unk>': 0,
             '<pad>': 1,
             'the': 2,
             'a': 3,
             'and': 4,
             'of': 5,
             'to': 6,
             'is': 7,
             'in': 8,
             'i': 9,
             'this': 10,
             'that': 11,
             'it': 12,
             '/><br': 13,
             'was': 14,
             'as': 15,
             'for': 16,
             'with': 17,
             'but': 18,
             'on': 19,
             'movie': 20,
             'his': 21,
             'are': 22,
             'not': 23,
             'film': 24,
             'you': 25,
             'have': 26,
             'he': 27,
             'be': 28,
             'at': 29,
             'one': 30,
             'by': 31,
             'an': 32,
             'they': 33,
             'from': 34,
             'all': 35,
             'who': 36,
             '

In [60]:
len(TEXT.vocab.stoi)

10002

In [117]:
train_iter,text_iter = torchtext.legacy.data.BucketIterator.splits(
                                                    (train,test),
                                                    batch_size=120)

In [118]:
b = next(iter(train_iter))

In [119]:
b.text[0]

tensor([   50,     9,    82,   308,     0,     9,   367,   323,    18,    98,
            5,     2,   336,     5,  4565,     0,   106,  3305,     0,  1328,
          214,     2,   304,    77,     5,    79,     0,    27,   397,     4,
         3564,     0,    87,  9386,    92,     0,   685,  1458,     5,     3,
          160,   243,     6,  1119,   645,    40,    23,     6,   494,    21,
         1891,    40,  9753,   402,    37,     0,     6,   472,    18,   691,
         1147,     0,     9,  1969,     6,    61,  1105,     2,  3295,   190,
          119,     2,  6235,     4,     0,    20,     0,   182,     5,     2,
            0,     0,     0,     4,    35,     5,   115,   180,    59,  2663,
           34,     0,     2,     0,     0,  6235,    29,   219,   113,    12,
          191,    99, 10000,    43,   203,    18,     0,   477,    34,    48,
            9,     0,     0,   525,    37,    33,   377,     6,     2,     0,
            0,   145,     0,   145,     0,     0,    13,  2418, 

In [120]:
b.label.shape

torch.Size([120])

In [157]:
b.label

tensor([2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1,
        1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1,
        2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1,
        2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1,
        1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2])

# 创建模型

In [167]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # 将10002的词床用 100大小的张量表示，每个单词都用长度为100的张量表示
        self.em = nn.Embedding(len(TEXT.vocab.stoi),100) #batch * 200 ---> batch*200*100
        self.fc1 = nn.Linear(200*100,1024)
        self.fc2 = nn.Linear(1024,3)
    def forward(self,x):
        x = self.em(x) #首先进入词向量表示
        x = x.view(x.size(0),-1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [168]:
model = Net()
model

Net(
  (em): Embedding(307605, 100)
  (fc1): Linear(in_features=20000, out_features=1024, bias=True)
  (fc2): Linear(in_features=1024, out_features=3, bias=True)
)

In [169]:
if torch.cuda.is_available():
    model.to('cuda')

In [170]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

In [171]:
def fit(epoch, model, trainloader, testloader):
    correct = 0
    total = 0
    running_loss = 0
    
    model.train()
    for b in trainloader:
        x, y = b.text, b.label
        if torch.cuda.is_available():
            x, y = b.text.to('cuda'), b.label.to('cuda')
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        with torch.no_grad():
            y_pred = torch.argmax(y_pred, dim=1)
            correct += (y_pred == y).sum().item()
            total += y.size(0)
            running_loss += loss.item()
#    exp_lr_scheduler.step()
    epoch_loss = running_loss / len(trainloader.dataset)
    epoch_acc = correct / total
        
        
    test_correct = 0
    test_total = 0
    test_running_loss = 0 
    
    model.eval()
    with torch.no_grad():
        for b in testloader:
            x, y = b.text, b.label
            if torch.cuda.is_available():
                x, y = x.to('cuda'), y.to('cuda')
            y_pred = model(x)
            loss = loss_fn(y_pred, y)
            y_pred = torch.argmax(y_pred, dim=1)
            test_correct += (y_pred == y).sum().item()
            test_total += y.size(0)
            test_running_loss += loss.item()
    
    epoch_test_loss = test_running_loss / len(testloader.dataset)
    epoch_test_acc = test_correct / test_total
    
        
    print('epoch: ', epoch, 
          'loss： ', round(epoch_loss, 3),
          'accuracy:', round(epoch_acc, 3),
          'test_loss： ', round(epoch_test_loss, 3),
          'test_accuracy:', round(epoch_test_acc, 3)
             )
        
    return epoch_loss, epoch_acc, epoch_test_loss, epoch_test_acc

In [172]:
epochs = 10

In [173]:
train_loss = []
train_acc = []
test_loss = []
test_acc = []

for epoch in range(epochs):
    epoch_loss, epoch_acc, epoch_test_loss, epoch_test_acc = fit(epoch,
                                                                 model,
                                                                 train_iter,
                                                                 text_iter)
    train_loss.append(epoch_loss)
    train_acc.append(epoch_acc)
    test_loss.append(epoch_test_loss)
    test_acc.append(epoch_test_acc)

KeyboardInterrupt: 

# 使用预训练模型

In [175]:
TEXT.build_vocab(train,vectors=GloVe(name='6B',dim=100),
                max_size = 20000,min_freq = 10)

.vector_cache\glove.6B.zip:   9%|████▍                                            | 77.9M/862M [12:07<2:01:59, 107kB/s]


KeyboardInterrupt: 